// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import SubdivisionResidenceController from "./subdivision_residence_controller"
application.register("SubdivisionResidence", SubdivisionResidenceController)

import WaterBillingTransactionsController from "./water_billing_transactions_controller"
application.register("WaterBillingTransactions", WaterBillingTransactionsController)

import MonthlyDueTransactionsController from "./monthly_due_transactions_controller"
application.register("MonthlyDueTransactions", MonthlyDueTransactionsController)
